/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sm.AAM.graficos.RectanguloRedondeado;

/**
 * Crea un JInternalFrma
 *
 * @author Antonio
 */
public class CambiarCurvaRectangulo extends javax.swing.JInternalFrame {

    VentanaInterna vi = null;
    RectanguloRedondeado rect = null;

    /**
     * Crea un objeto de tipo CambiarCurvaRectangulo
     *
     * @param vi - VentanaInterna
     */
    public CambiarCurvaRectangulo(VentanaInterna vi) {
        initComponents();
        if (vi != null && vi.isImagen()) {
            this.vi = vi;
            if (((VentanaInternaImagen) vi).getLienzo().getFigura() != null && ((VentanaInternaImagen) vi).getLienzo().getFigura() instanceof RectanguloRedondeado) {
                this.rect = (RectanguloRedondeado) ((VentanaInternaImagen) vi).getLienzo().getFigura();
                this.jAltoCurva.getModel().setValue(((RectanguloRedondeado) ((VentanaInternaImagen) vi).getLienzo().getFigura()).getArcHeight());
                this.jAnchoCurva.getModel().setValue(((RectanguloRedondeado) ((VentanaInternaImagen) vi).getLienzo().getFigura()).getArcWidth());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jAnchoCurva = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jAltoCurva = new javax.swing.JSpinner();

        setClosable(true);
        setTitle("Cambiar curva del rectángulo");
        setPreferredSize(new java.awt.Dimension(199, 90));

        jAceptar.setText("Aceptar");
        jAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(jAceptar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setMaximumSize(new java.awt.Dimension(69, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(69, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(69, 25));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("Ancho");
        jLabel1.setPreferredSize(new java.awt.Dimension(39, 25));
        jPanel1.add(jLabel1);

        jAnchoCurva.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(20), Integer.valueOf(0), null, Integer.valueOf(5)));
        jAnchoCurva.setToolTipText("");
        jAnchoCurva.setPreferredSize(new java.awt.Dimension(47, 30));
        jAnchoCurva.setValue(20);
        jAnchoCurva.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAnchoCurvaStateChanged(evt);
            }
        });
        jPanel1.add(jAnchoCurva);

        jLabel2.setText("Alto");
        jLabel2.setPreferredSize(new java.awt.Dimension(39, 25));
        jPanel1.add(jLabel2);

        jAltoCurva.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(20), Integer.valueOf(20), null, Integer.valueOf(5)));
        jAltoCurva.setPreferredSize(new java.awt.Dimension(47, 30));
        jAltoCurva.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jAltoCurvaStateChanged(evt);
            }
        });
        jPanel1.add(jAltoCurva);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Cierra la ventana
     *
     * @param evt - Evento producido por el ratón
     */
    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Redimensionar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAceptarActionPerformed
    /**
     * Cambia el ancho de la curva, de las esquinas
     *
     * @param evt - Evento producido por el ratón
     */
    private void jAnchoCurvaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAnchoCurvaStateChanged
        this.rect = (RectanguloRedondeado) ((VentanaInternaImagen) vi).getLienzo().getFigura();
        if (this.rect != null && this.rect instanceof RectanguloRedondeado) {
            this.rect.setArcWidth(Integer.parseInt(this.jAnchoCurva.getValue().toString()));
            ((VentanaInternaImagen) vi).getLienzo().repaint();
        }
    }//GEN-LAST:event_jAnchoCurvaStateChanged
    /**
     * Cambia el alto de la curva, de las esquinas
     *
     * @param evt - Evento producido por el ratón
     */
    private void jAltoCurvaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jAltoCurvaStateChanged
        this.rect = (RectanguloRedondeado) ((VentanaInternaImagen) vi).getLienzo().getFigura();
        if (this.rect != null && this.rect instanceof RectanguloRedondeado) {
            this.rect.setArcHeight(Integer.parseInt(this.jAltoCurva.getValue().toString()));
            ((VentanaInternaImagen) vi).getLienzo().repaint();
        }
    }//GEN-LAST:event_jAltoCurvaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JSpinner jAltoCurva;
    private javax.swing.JSpinner jAnchoCurva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
