/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.awt.Color;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import sm.AAM.graficos.Forma;
import sm.AAM.graficos.Relleno;
import sm.AAM.graficos.RellenoSimple;

/**
 * Clase que crea una ventana interna, en dicha ventana interna podremos
 * modificar el valor del relleno
 *
 * @author Antonio
 */
public class Rellenos extends javax.swing.JInternalFrame {

    private Color color = Color.BLACK;
    private VentanaInterna vi;
    private Forma figura;
    private Relleno relleno;
    private int rojo = 0;
    private int verde = 0;
    private int azul = 0;
    private Icon[] rellenos;

    /**
     * Crea un objeto de tipo Rellenos, se le pasa como parámetro una
     * ventanaInterna
     *
     * @param ventanaInterna - JInternalframe de tipo ventanaInterna
     */
    public Rellenos(VentanaInterna ventanaInterna) {
        initComponents();
        this.vi = ventanaInterna;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jRellenar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jPaletaColores = new javax.swing.JColorChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rellenar");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(633, 396));
        setMinimumSize(new java.awt.Dimension(633, 396));
        setPreferredSize(new java.awt.Dimension(633, 396));

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jRellenar.setText("Aceptar");
        jRellenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRellenarActionPerformed(evt);
            }
        });
        jPanel3.add(jRellenar, new java.awt.GridBagConstraints());

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel3.add(Cancelar, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jPaletaColores, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cancela la acción y cierra la ventana
     *
     * @param evt - Evento producido por el ratón
     */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        try {
            relleno = null;
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Redimensionar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * Rellenará la figurá seleccionada, con el color de la variable color.
     *
     * @param evt - Evento producido por el ratón
     */
    private void jRellenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRellenarActionPerformed
        if (vi.isImagen()) {
            this.color = this.jPaletaColores.getColor();
            relleno = new RellenoSimple(this.color);
            ((VentanaInternaImagen) vi).getLienzo().setRelleno(relleno);

        }
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Redimensionar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jRellenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JColorChooser jPaletaColores;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jRellenar;
    // End of variables declaration//GEN-END:variables

}
