/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.awt.Color;
import java.awt.geom.Point2D;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import sm.AAM.graficos.Forma;
import sm.AAM.graficos.Relleno;
import sm.AAM.graficos.RellenoDegradado;
import sm.AAM.graficos.RellenoRadial;

/**
 * Clase que crea una ventana interna, en dicha ventana interna podremos
 * modificar el valor del relleno
 *
 * @author Antonio
 */
public class RellenosDegradado extends javax.swing.JInternalFrame {

    private Color frente;
    private Color fondo;
    private int tipoDegradado;
    private VentanaInterna vi;
    private Forma figura;
    Relleno relleno;
    private Icon[] rellenos;

    /**
     * Crea un objeto de tipo RellenosDegradado, se le pasa como parámetro una
     * ventanaInterna
     *
     * @param ventanaInterna - JInternalframe de tipo ventanaInterna
     */
    public RellenosDegradado(VentanaInterna ventanaInterna) {
        this.vi = ventanaInterna;
        if (((VentanaInternaImagen) vi).getLienzo().getFigura() == null) {
            JOptionPane.showMessageDialog(null, "No puedes aplicar rellenos degrados sin tener seleccionada una forma");
            try {
                this.setClosed(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Redimensionar.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            initComponents();
            frente = Color.BLACK;
            fondo = Color.ORANGE;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelColores = new javax.swing.JPanel();
        jPanelColorFrente = new javax.swing.JPanel();
        jColorBlancoFrente = new javax.swing.JToggleButton();
        jColorVerdeFrente = new javax.swing.JToggleButton();
        jColorRojoFrente = new javax.swing.JToggleButton();
        jColorNegroFrente = new javax.swing.JToggleButton();
        jColorAmarilloFrente = new javax.swing.JToggleButton();
        jColorAzulFrente = new javax.swing.JToggleButton();
        jColoresFrente = new javax.swing.JButton();
        jPanelColorFondo = new javax.swing.JPanel();
        jColorBlancoFondo = new javax.swing.JToggleButton();
        jColorVerdeFondo = new javax.swing.JToggleButton();
        jColorRojoFondo = new javax.swing.JToggleButton();
        jColorNegroFondo = new javax.swing.JToggleButton();
        jColorAmarilloFondo = new javax.swing.JToggleButton();
        jColorAzulFondo = new javax.swing.JToggleButton();
        jColoresFondo = new javax.swing.JButton();
        jPanelDegradado = new javax.swing.JPanel();
        rellenos=new Icon[]{new javax.swing.ImageIcon(getClass().getResource("/iconos/GradienteVertical.png")),new javax.swing.ImageIcon(getClass().getResource("/iconos/GradienteHorizontal.png")),new javax.swing.ImageIcon(getClass().getResource("/iconos/GradienteDiagonal.png")),new javax.swing.ImageIcon(getClass().getResource("/iconos/GradienteCircular.png")),new javax.swing.ImageIcon(getClass().getResource("/iconos/GradienteHorizontalCiclico.png")),new javax.swing.ImageIcon(getClass().getResource("/iconos/GradienteVerticalCiclico.png"))};
        jDireccionDegradado = new javax.swing.JComboBox(rellenos);
        jPanelColoresActuales = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanelColorFrenteFinal = new javax.swing.JPanel();
        jPanelColorFondoFinal = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jBDegradado = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rellenar");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(456, 300));
        setMinimumSize(new java.awt.Dimension(456, 300));
        setPreferredSize(new java.awt.Dimension(456, 250));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanelColorFrente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Frente:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {3};
        jPanel1Layout.rowHeights = new int[] {2};
        jPanelColorFrente.setLayout(jPanel1Layout);

        jColorBlancoFrente.setBackground(new java.awt.Color(255, 255, 255));
        jColorBlancoFrente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jColorBlancoFrente.setFocusable(false);
        jColorBlancoFrente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorBlancoFrente.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorBlancoFrente.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorBlancoFrente.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorBlancoFrente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorBlancoFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorBlancoFrenteActionPerformed(evt);
            }
        });
        jPanelColorFrente.add(jColorBlancoFrente, new java.awt.GridBagConstraints());

        jColorVerdeFrente.setBackground(new java.awt.Color(0, 204, 0));
        jColorVerdeFrente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jColorVerdeFrente.setFocusable(false);
        jColorVerdeFrente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorVerdeFrente.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorVerdeFrente.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorVerdeFrente.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorVerdeFrente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorVerdeFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorVerdeFrenteActionPerformed(evt);
            }
        });
        jPanelColorFrente.add(jColorVerdeFrente, new java.awt.GridBagConstraints());

        jColorRojoFrente.setBackground(new java.awt.Color(255, 0, 0));
        jColorRojoFrente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jColorRojoFrente.setFocusable(false);
        jColorRojoFrente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorRojoFrente.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorRojoFrente.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorRojoFrente.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorRojoFrente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorRojoFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorRojoFrenteActionPerformed(evt);
            }
        });
        jPanelColorFrente.add(jColorRojoFrente, new java.awt.GridBagConstraints());

        jColorNegroFrente.setBackground(new java.awt.Color(0, 0, 0));
        jColorNegroFrente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jColorNegroFrente.setFocusable(false);
        jColorNegroFrente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorNegroFrente.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorNegroFrente.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorNegroFrente.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorNegroFrente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorNegroFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorNegroFrenteActionPerformed(evt);
            }
        });
        jPanelColorFrente.add(jColorNegroFrente, new java.awt.GridBagConstraints());

        jColorAmarilloFrente.setBackground(new java.awt.Color(255, 255, 0));
        jColorAmarilloFrente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jColorAmarilloFrente.setFocusable(false);
        jColorAmarilloFrente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorAmarilloFrente.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorAmarilloFrente.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorAmarilloFrente.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorAmarilloFrente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorAmarilloFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorAmarilloFrenteActionPerformed(evt);
            }
        });
        jPanelColorFrente.add(jColorAmarilloFrente, new java.awt.GridBagConstraints());

        jColorAzulFrente.setBackground(new java.awt.Color(0, 0, 204));
        jColorAzulFrente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jColorAzulFrente.setFocusable(false);
        jColorAzulFrente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorAzulFrente.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorAzulFrente.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorAzulFrente.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorAzulFrente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorAzulFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorAzulFrenteActionPerformed(evt);
            }
        });
        jPanelColorFrente.add(jColorAzulFrente, new java.awt.GridBagConstraints());

        jColoresFrente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/emblem_art2 .png"))); // NOI18N
        jColoresFrente.setFocusable(false);
        jColoresFrente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColoresFrente.setMaximumSize(new java.awt.Dimension(31, 33));
        jColoresFrente.setMinimumSize(new java.awt.Dimension(31, 33));
        jColoresFrente.setPreferredSize(new java.awt.Dimension(31, 33));
        jColoresFrente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColoresFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColoresFrenteActionPerformed(evt);
            }
        });
        jPanelColorFrente.add(jColoresFrente, new java.awt.GridBagConstraints());

        jPanelColorFondo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fondo:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        jPanelColorFondo.setLayout(new java.awt.GridBagLayout());

        jColorBlancoFondo.setBackground(new java.awt.Color(255, 255, 255));
        jColorBlancoFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jColorBlancoFondo.setFocusable(false);
        jColorBlancoFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorBlancoFondo.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorBlancoFondo.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorBlancoFondo.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorBlancoFondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorBlancoFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorBlancoFondoActionPerformed(evt);
            }
        });
        jPanelColorFondo.add(jColorBlancoFondo, new java.awt.GridBagConstraints());

        jColorVerdeFondo.setBackground(new java.awt.Color(0, 204, 0));
        jColorVerdeFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 0)));
        jColorVerdeFondo.setFocusable(false);
        jColorVerdeFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorVerdeFondo.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorVerdeFondo.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorVerdeFondo.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorVerdeFondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorVerdeFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorVerdeFondoActionPerformed(evt);
            }
        });
        jPanelColorFondo.add(jColorVerdeFondo, new java.awt.GridBagConstraints());

        jColorRojoFondo.setBackground(new java.awt.Color(255, 0, 0));
        jColorRojoFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jColorRojoFondo.setFocusable(false);
        jColorRojoFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorRojoFondo.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorRojoFondo.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorRojoFondo.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorRojoFondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorRojoFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorRojoFondoActionPerformed(evt);
            }
        });
        jPanelColorFondo.add(jColorRojoFondo, new java.awt.GridBagConstraints());

        jColorNegroFondo.setBackground(new java.awt.Color(0, 0, 0));
        jColorNegroFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jColorNegroFondo.setFocusable(false);
        jColorNegroFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorNegroFondo.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorNegroFondo.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorNegroFondo.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorNegroFondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorNegroFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorNegroFondoActionPerformed(evt);
            }
        });
        jPanelColorFondo.add(jColorNegroFondo, new java.awt.GridBagConstraints());

        jColorAmarilloFondo.setBackground(new java.awt.Color(255, 255, 0));
        jColorAmarilloFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jColorAmarilloFondo.setFocusable(false);
        jColorAmarilloFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorAmarilloFondo.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorAmarilloFondo.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorAmarilloFondo.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorAmarilloFondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorAmarilloFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorAmarilloFondoActionPerformed(evt);
            }
        });
        jPanelColorFondo.add(jColorAmarilloFondo, new java.awt.GridBagConstraints());

        jColorAzulFondo.setBackground(new java.awt.Color(0, 0, 204));
        jColorAzulFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jColorAzulFondo.setFocusable(false);
        jColorAzulFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColorAzulFondo.setMaximumSize(new java.awt.Dimension(30, 30));
        jColorAzulFondo.setMinimumSize(new java.awt.Dimension(30, 30));
        jColorAzulFondo.setPreferredSize(new java.awt.Dimension(30, 30));
        jColorAzulFondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColorAzulFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColorAzulFondoActionPerformed(evt);
            }
        });
        jPanelColorFondo.add(jColorAzulFondo, new java.awt.GridBagConstraints());

        jColoresFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/emblem_art2 .png"))); // NOI18N
        jColoresFondo.setFocusable(false);
        jColoresFondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jColoresFondo.setMaximumSize(new java.awt.Dimension(31, 33));
        jColoresFondo.setMinimumSize(new java.awt.Dimension(31, 33));
        jColoresFondo.setPreferredSize(new java.awt.Dimension(31, 33));
        jColoresFondo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jColoresFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jColoresFondoActionPerformed(evt);
            }
        });
        jPanelColorFondo.add(jColoresFondo, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanelColoresLayout = new javax.swing.GroupLayout(jPanelColores);
        jPanelColores.setLayout(jPanelColoresLayout);
        jPanelColoresLayout.setHorizontalGroup(
            jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelColorFrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelColorFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelColoresLayout.setVerticalGroup(
            jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelColorFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelColores);

        jPanelDegradado.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección del degradado"));
        jPanelDegradado.setMinimumSize(new java.awt.Dimension(161, 160));
        jPanelDegradado.setPreferredSize(new java.awt.Dimension(161, 183));

        jDireccionDegradado.setToolTipText("");
        jDireccionDegradado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP));
        jDireccionDegradado.setMinimumSize(new java.awt.Dimension(30, 53));
        jDireccionDegradado.setPreferredSize(new java.awt.Dimension(90, 53));
        jDireccionDegradado.setRenderer(new sm.AAM.iu.Iconos());
        jDireccionDegradado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDireccionDegradadoActionPerformed(evt);
            }
        });
        jPanelDegradado.add(jDireccionDegradado);

        jPanelColoresActuales.setPreferredSize(new java.awt.Dimension(110, 80));

        jTextField1.setBackground(new java.awt.Color(218, 218, 218));
        jTextField1.setText("Frente");
        jTextField1.setBorder(null);
        jPanelColoresActuales.add(jTextField1);

        jTextField2.setBackground(new java.awt.Color(218, 218, 218));
        jTextField2.setText("Fondo");
        jTextField2.setBorder(null);
        jPanelColoresActuales.add(jTextField2);

        jPanelColorFrenteFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelColorFrenteFinal.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelColorFrenteFinalLayout = new javax.swing.GroupLayout(jPanelColorFrenteFinal);
        jPanelColorFrenteFinal.setLayout(jPanelColorFrenteFinalLayout);
        jPanelColorFrenteFinalLayout.setHorizontalGroup(
            jPanelColorFrenteFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanelColorFrenteFinalLayout.setVerticalGroup(
            jPanelColorFrenteFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanelColoresActuales.add(jPanelColorFrenteFinal);

        jPanelColorFondoFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelColorFondoFinal.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanelColorFondoFinalLayout = new javax.swing.GroupLayout(jPanelColorFondoFinal);
        jPanelColorFondoFinal.setLayout(jPanelColorFondoFinalLayout);
        jPanelColorFondoFinalLayout.setHorizontalGroup(
            jPanelColorFondoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanelColorFondoFinalLayout.setVerticalGroup(
            jPanelColorFondoFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanelColoresActuales.add(jPanelColorFondoFinal);

        jPanelDegradado.add(jPanelColoresActuales);

        getContentPane().add(jPanelDegradado);

        jPanelOpciones.setMinimumSize(new java.awt.Dimension(233, 53));
        jPanelOpciones.setPreferredSize(new java.awt.Dimension(456, 30));
        jPanelOpciones.setLayout(new java.awt.GridBagLayout());

        jBDegradado.setText("Aceptar");
        jBDegradado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDegradadoActionPerformed(evt);
            }
        });
        jPanelOpciones.add(jBDegradado, new java.awt.GridBagConstraints());

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanelOpciones.add(Cancelar, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelOpciones);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Asigna a la variable frente el color blanco
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorBlancoFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorBlancoFrenteActionPerformed
        frente = Color.WHITE;
        this.jPanelColorFrenteFinal.setBackground(frente);

    }//GEN-LAST:event_jColorBlancoFrenteActionPerformed
    /**
     * Asigna a la variable frente el color verde
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorVerdeFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorVerdeFrenteActionPerformed
        frente = Color.GREEN;
        this.jPanelColorFrenteFinal.setBackground(frente);
    }//GEN-LAST:event_jColorVerdeFrenteActionPerformed
    /**
     * Asigna a la variable frente el color rojo
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorRojoFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorRojoFrenteActionPerformed
        frente = Color.RED;
        this.jPanelColorFrenteFinal.setBackground(frente);
    }//GEN-LAST:event_jColorRojoFrenteActionPerformed
    /**
     * Asigna a la variable frente el color negro
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorNegroFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorNegroFrenteActionPerformed
        frente = Color.BLACK;
        this.jPanelColorFrenteFinal.setBackground(frente);
    }//GEN-LAST:event_jColorNegroFrenteActionPerformed
    /**
     * Asigna a la variable frente el color amarillo
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorAmarilloFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorAmarilloFrenteActionPerformed
        frente = Color.YELLOW;
        this.jPanelColorFrenteFinal.setBackground(frente);
    }//GEN-LAST:event_jColorAmarilloFrenteActionPerformed
    /**
     * Asigna a la variable frente el color azúl
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorAzulFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorAzulFrenteActionPerformed
        frente = Color.BLUE;
        this.jPanelColorFrenteFinal.setBackground(frente);
    }//GEN-LAST:event_jColorAzulFrenteActionPerformed
    /**
     * Asigna a la variable fondo el color blanco
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorBlancoFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorBlancoFondoActionPerformed
        fondo = Color.WHITE;
        this.jPanelColorFondoFinal.setBackground(fondo);
    }//GEN-LAST:event_jColorBlancoFondoActionPerformed
    /**
     * Asigna a la variable fondo el color verde
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorVerdeFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorVerdeFondoActionPerformed
        fondo = Color.GREEN;
        this.jPanelColorFondoFinal.setBackground(fondo);
    }//GEN-LAST:event_jColorVerdeFondoActionPerformed
    /**
     * Asigna a la variable fondo el color rojo
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorRojoFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorRojoFondoActionPerformed
        fondo = Color.RED;
        this.jPanelColorFondoFinal.setBackground(fondo);
    }//GEN-LAST:event_jColorRojoFondoActionPerformed
    /**
     * Asigna a la variable fondo el color negro
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorNegroFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorNegroFondoActionPerformed
        fondo = Color.BLACK;
        this.jPanelColorFondoFinal.setBackground(fondo);
    }//GEN-LAST:event_jColorNegroFondoActionPerformed
    /**
     * Asigna a la variable fondo el color amarillo
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorAmarilloFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorAmarilloFondoActionPerformed
        fondo = Color.YELLOW;
        this.jPanelColorFondoFinal.setBackground(fondo);
    }//GEN-LAST:event_jColorAmarilloFondoActionPerformed
    /**
     * Asigna a la variable fondo el color azúl
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColorAzulFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColorAzulFondoActionPerformed
        fondo = Color.BLUE;
        this.jPanelColorFondoFinal.setBackground(fondo);
    }//GEN-LAST:event_jColorAzulFondoActionPerformed
    /**
     * Cancela la acción y cierra la ventana
     *
     * @param evt - Evento producido por el ratón
     */
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        try {
            relleno = null;
            this.setClosed(true);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(Redimensionar.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancelarActionPerformed
    /**
     * Selecciona el tipo de degradado
     *
     * @param evt - Evento producido por el ratón
     */
    private void jDireccionDegradadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDireccionDegradadoActionPerformed
        this.tipoDegradado = this.jDireccionDegradado.getSelectedIndex();
    }//GEN-LAST:event_jDireccionDegradadoActionPerformed
    /**
     * Establece según el tipo de degradado seleccionado, el degrado a crear. Se
     * creará usando los colores de las variables frente y fondo
     *
     * @param evt - Evento producido por el ratón
     */
    private void jBDegradadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDegradadoActionPerformed
        figura = ((VentanaInternaImagen) vi).getLienzo().getFigura();
        if (figura != null) {
            if (this.tipoDegradado == 0) {
                Point2D puntoInicial = new Point2D.Double(figura.getP1().getX(), 0);
                Point2D puntoFinal = new Point2D.Double(figura.getP2().getX(), 0);
                relleno = new RellenoDegradado(puntoInicial, frente, puntoFinal, fondo);

            } else if (this.tipoDegradado == 1) {
                Point2D puntoInicial = new Point2D.Double(0, figura.getP1().getY());
                Point2D puntoFinal = new Point2D.Double(0, figura.getP2().getY());
                relleno = new RellenoDegradado(puntoInicial, frente, puntoFinal, fondo);

            } else if (this.tipoDegradado == 2) {
                double xFinal = Math.abs(figura.getP2().getX() - figura.getP1().getX());
                double yFinal = Math.abs(figura.getP2().getY() - figura.getP1().getY());
                double distancia = Math.sqrt(Math.pow(xFinal, 2) + Math.pow(yFinal, 2));
                Point2D puntoInicial = new Point2D.Double(figura.getP1().getX(), figura.getP1().getY());
                Point2D puntoFinal = new Point2D.Double(figura.getP1().getX() + distancia / 2, figura.getP1().getY() + distancia / 2);
                relleno = new RellenoDegradado(puntoInicial, frente, puntoFinal, fondo);

            } else if (this.tipoDegradado == 3) {
                Point2D centro = new Point2D.Double(figura.getBounds().getCenterX(), figura.getBounds().getCenterY());
                Color[] colores = {this.frente, this.fondo};
                float radius = 10;
                float[] dist = {0.5f, 1.0f};
                relleno = new RellenoRadial(centro, radius, dist, colores);

            } else if (this.tipoDegradado == 4) {
                Point2D puntoInicial = new Point2D.Double(0, 0);
                Point2D puntoFinal = new Point2D.Double(0, 10);
                relleno = new RellenoDegradado(puntoInicial, frente, puntoFinal, fondo, true);
            } else if (this.tipoDegradado == 5) {
                Point2D puntoInicial = new Point2D.Double(0, 0);
                Point2D puntoFinal = new Point2D.Double(10, 0);
                relleno = new RellenoDegradado(puntoInicial, frente, puntoFinal, fondo, true);
            }
            figura.setAtributo(relleno);
        }
        try {
            this.setClosed(true);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(Redimensionar.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBDegradadoActionPerformed

    /**
     * Asigna a la variable frente el color escogido en la paleta de colores
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColoresFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColoresFrenteActionPerformed
        this.frente = activarPaleta();
        this.jPanelColorFrenteFinal.setBackground(frente);
    }//GEN-LAST:event_jColoresFrenteActionPerformed
    /**
     * Asigna a la variable fondo el color escogido en la paleta de colores
     *
     * @param evt - Evento producido por el ratón
     */
    private void jColoresFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jColoresFondoActionPerformed
        this.fondo = activarPaleta();
        this.jPanelColorFondoFinal.setBackground(fondo);
        this.jPanelColorFrenteFinal.setBackground(frente);
    }//GEN-LAST:event_jColoresFondoActionPerformed
    /**
     * Activa una ventana con una paleta de colores
     *
     * @return - Devuelve un color
     */
    public Color activarPaleta() {
        JColorChooser ventanaDeColores = new JColorChooser();
        return ventanaDeColores.showDialog(null, "Seleccione un Color", Color.gray);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton jBDegradado;
    private javax.swing.JToggleButton jColorAmarilloFondo;
    private javax.swing.JToggleButton jColorAmarilloFrente;
    private javax.swing.JToggleButton jColorAzulFondo;
    private javax.swing.JToggleButton jColorAzulFrente;
    private javax.swing.JToggleButton jColorBlancoFondo;
    private javax.swing.JToggleButton jColorBlancoFrente;
    private javax.swing.JToggleButton jColorNegroFondo;
    private javax.swing.JToggleButton jColorNegroFrente;
    private javax.swing.JToggleButton jColorRojoFondo;
    private javax.swing.JToggleButton jColorRojoFrente;
    private javax.swing.JToggleButton jColorVerdeFondo;
    private javax.swing.JToggleButton jColorVerdeFrente;
    private javax.swing.JButton jColoresFondo;
    private javax.swing.JButton jColoresFrente;
    private javax.swing.JComboBox jDireccionDegradado;
    private javax.swing.JPanel jPanelColorFondo;
    private javax.swing.JPanel jPanelColorFondoFinal;
    private javax.swing.JPanel jPanelColorFrente;
    private javax.swing.JPanel jPanelColorFrenteFinal;
    private javax.swing.JPanel jPanelColores;
    private javax.swing.JPanel jPanelColoresActuales;
    private javax.swing.JPanel jPanelDegradado;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
