/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import sm.AAM.imagen.TintOp;

/**
 * Clase que crea un jInternalFrame
 *
 * @author Antonio
 */
public class Tintado extends javax.swing.JInternalFrame {

    private VentanaInternaImagen vi;
    private Color color;
    private BufferedImage imgSource = null;
    private BufferedImage imgdest = null;

    /**
     * Creas un nuevo objeto de la clase Tintado
     *
     * @param vi - VentanaInternaImagen
     */
    public Tintado(VentanaInternaImagen vi) {
        initComponents();
        this.vi = vi;
        imgSource = vi.getLienzo().getImage();
        this.jPanelPrevisualizacion.setPreferredSize(new Dimension(imgSource.getWidth(), imgSource.getHeight()));
        this.jPanelPrevisualizacion.setIcon(new ImageIcon(imgSource));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jColorMuestra = new javax.swing.JPanel();
        jPanelColor = new javax.swing.JButton();
        jGradoTintado = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jAceptar = new javax.swing.JButton();
        jCancelar = new javax.swing.JButton();
        jPanelPrevisualizacion = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tintado");
        setPreferredSize(new java.awt.Dimension(605, 407));

        jPanel1.setMinimumSize(new java.awt.Dimension(604, 302));
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 180));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(180, 160));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 2));

        jPanel3.setPreferredSize(new java.awt.Dimension(170, 80));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));

        jLabel1.setText("Color del tintado");
        jPanel3.add(jLabel1);

        jColorMuestra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jColorMuestra.setMaximumSize(new java.awt.Dimension(31, 31));
        jColorMuestra.setMinimumSize(new java.awt.Dimension(31, 31));
        jColorMuestra.setPreferredSize(new java.awt.Dimension(31, 31));

        javax.swing.GroupLayout jColorMuestraLayout = new javax.swing.GroupLayout(jColorMuestra);
        jColorMuestra.setLayout(jColorMuestraLayout);
        jColorMuestraLayout.setHorizontalGroup(
            jColorMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        jColorMuestraLayout.setVerticalGroup(
            jColorMuestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel3.add(jColorMuestra);

        jPanelColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Colores.png"))); // NOI18N
        jPanelColor.setToolTipText("Paleta de colores");
        jPanelColor.setFocusable(false);
        jPanelColor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelColor.setMaximumSize(new java.awt.Dimension(31, 33));
        jPanelColor.setMinimumSize(new java.awt.Dimension(31, 33));
        jPanelColor.setPreferredSize(new java.awt.Dimension(31, 33));
        jPanelColor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelColor.addActionListener(formListener);
        jPanel3.add(jPanelColor);

        jGradoTintado.setPaintLabels(true);
        jGradoTintado.setPaintTicks(true);
        jGradoTintado.setValue(0);
        jGradoTintado.addChangeListener(formListener);
        jPanel3.add(jGradoTintado);

        jPanel4.add(jPanel3);

        jAceptar.setText("Aceptar");
        jAceptar.addActionListener(formListener);
        jPanel2.add(jAceptar);

        jCancelar.setText("Cancelar");
        jCancelar.addActionListener(formListener);
        jPanel2.add(jCancelar);

        jPanel4.add(jPanel2);

        jPanel1.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanelPrevisualizacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        jPanelPrevisualizacion.setMaximumSize(new java.awt.Dimension(30000, 300000));
        jPanelPrevisualizacion.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanelPrevisualizacion.setPreferredSize(new java.awt.Dimension(320, 320));
        jPanel1.add(jPanelPrevisualizacion, java.awt.BorderLayout.EAST);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, javax.swing.event.ChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == jPanelColor) {
                Tintado.this.jPanelColorActionPerformed(evt);
            }
            else if (evt.getSource() == jAceptar) {
                Tintado.this.jAceptarActionPerformed(evt);
            }
            else if (evt.getSource() == jCancelar) {
                Tintado.this.jCancelarActionPerformed(evt);
            }
        }

        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (evt.getSource() == jGradoTintado) {
                Tintado.this.jGradoTintadoStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents
/**
     * Método encargado de lanzar la ventana de selección de colores
     *
     * @param evt - Evento producido por el ratón
     */
    private void jPanelColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPanelColorActionPerformed
        this.activarPaleta();
        this.jColorMuestra.setBackground(color);


    }//GEN-LAST:event_jPanelColorActionPerformed
    /**
     * Conforme vas moviendo el slider, vas generando unos estados, en este caso
     * el estado que generas es un nivel de tintado de la imagen. Para poder
     * hacer esto hay que declarar un tinOp con un valor de tintado, una vez
     * creada le aplicas a la imagen el filtro
     *
     * @param evt - Evento producido por el ratón
     */
    private void jGradoTintadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jGradoTintadoStateChanged
        float w = this.jGradoTintado.getValue() / 100.0f;
        if (color == null) {
            this.activarPaleta();
            this.jColorMuestra.setBackground(color);

        } else {
            TintOp tinOp = new TintOp(this.color, w);
            imgdest = tinOp.filter(imgSource, imgdest);
            this.jPanelPrevisualizacion.setIcon(new ImageIcon(imgdest));
            this.jPanelPrevisualizacion.repaint();
        }
    }//GEN-LAST:event_jGradoTintadoStateChanged
    /**
     * Aplicas los cambios a la imagen original
     *
     * @param evt - Evento producido por el ratón
     */
    private void jAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarActionPerformed
        vi.getLienzo().setImage(imgdest);
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Redimensionar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAceptarActionPerformed
    /**
     * Sales de la ventana sin aplicar ningún cambio
     *
     * @param evt - Evento producido por el ratón
     */
    private void jCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarActionPerformed
        try {
            this.setClosed(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Redimensionar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCancelarActionPerformed
    /**
     * Lanza una ventana con las paletas de color
     */
    public void activarPaleta() {
        JColorChooser ventanaDeColores = new JColorChooser();
        color = ventanaDeColores.showDialog(null, "Seleccione un Color", Color.gray);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptar;
    private javax.swing.JButton jCancelar;
    private javax.swing.JPanel jColorMuestra;
    private javax.swing.JSlider jGradoTintado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jPanelColor;
    private javax.swing.JLabel jPanelPrevisualizacion;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
